import avenir from './fonts/avenir'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={avenir.variable}>{children}</body>
        </html>
    )
}
